spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test01
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  profiles:
    active: local

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
